// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    partial class HotelListingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Data.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "United States",
                            ShortName = "US"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Canada",
                            ShortName = "CA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mexico",
                            ShortName = "MX"
                        },
                        new
                        {
                            Id = 4,
                            Name = "United Kingdom",
                            ShortName = "UK"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Germany",
                            ShortName = "DE"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Romania",
                            ShortName = "RO"
                        });
                });

            modelBuilder.Entity("API.Data.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "42 Sunset Blvd, Los Angeles, CA",
                            CountryId = 1,
                            Name = "Hotel California",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "1 Republic Square, Budapest",
                            CountryId = 6,
                            Name = "The Grand Budapest Hotel",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 3,
                            Address = "150 Piccadilly, London",
                            CountryId = 4,
                            Name = "The Ritz London",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 4,
                            Address = "100 Reforma Ave, Mexico City",
                            CountryId = 3,
                            Name = "Hotel Mexico City",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 5,
                            Address = "405 Spray Ave, Banff, AB",
                            CountryId = 2,
                            Name = "Fairmont Banff Springs",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 6,
                            Address = "50 Alexanderplatz, Berlin",
                            CountryId = 5,
                            Name = "Hotel Berlin Central",
                            Rating = 4.4000000000000004
                        });
                });

            modelBuilder.Entity("API.Data.Models.Hotel", b =>
                {
                    b.HasOne("API.Data.Models.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("API.Data.Models.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
